[feature-18] Address the network part of the game
NiskuT/Civilization pull request #118
Opened 2023-01-12 15:19 UTC by NiskuT

2023-01-12 20:02 UTC, lucas-mrq requested changes

2023-01-13 07:20 UTC, lucas-mrq approved these changes

2023-01-13 09:27 UTC, jard-111 commented on src/server/Server.cpp
> +            // a changer (appeler disconnect ?)
maybe write this comment as a "TODO" to find it quickly

2023-01-13 09:31 UTC, jard-111 submitted a review, later dismissed

2023-01-13 10:17 UTC, lucas-mrq approved these changes

2023-01-13 10:57 UTC, merged